/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Proxy } from './ERC1155Proxy';
export type { ERC20Proxy } from './ERC20Proxy';
export type { ERC721Proxy } from './ERC721Proxy';
export type { ExchangeContract } from './ExchangeContract';
export type { Forwarder } from './Forwarder';
export type { MultiAssetProxy } from './MultiAssetProxy';
export type { StaticCallProxy } from './StaticCallProxy';
