/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  StaticCallProxy,
  StaticCallProxyInterface,
} from '../../../ZeroEx/v3/StaticCallProxy';

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: 'assetData',
        type: 'bytes',
      },
      {
        name: 'from',
        type: 'address',
      },
      {
        name: 'to',
        type: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'transferFrom',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'getProxyId',
    outputs: [
      {
        name: '',
        type: 'bytes4',
      },
    ],
    payable: false,
    stateMutability: 'pure',
    type: 'function',
  },
];

export class StaticCallProxy__factory {
  static readonly abi = _abi;
  static createInterface(): StaticCallProxyInterface {
    return new utils.Interface(_abi) as StaticCallProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StaticCallProxy {
    return new Contract(address, _abi, signerOrProvider) as StaticCallProxy;
  }
}
